# Generated by Django 6.0.2 on 2026-03-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ar', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Critère',
                'verbose_name_plural': 'Critères',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='courses.seance')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.superviseur')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='NoteEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(0, 'منعدم'), (1, 'ضعيف'), (2, 'متوسط'), (3, 'حسن'), (4, 'حسن جدا')])),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.critere')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Note Évaluation',
                'unique_together': {('evaluation', 'critere')},
            },
        ),
    ]
