# Generated by Django 6.0.2 on 2026-07-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prof_majoration_mensuelle'),
        ('evaluations', '0003_seed_criteres_reels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_reference', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_mensuels', to='accounts.prof')),
                ('redige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire mensuel',
                'verbose_name_plural': 'Commentaires mensuels',
                'unique_together': {('prof', 'mois_reference')},
            },
        ),
    ]
