# Generated by Django 6.0.2 on 2026-08-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_backfill_evaluation_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='critere',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='critere',
            name='nom_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
