# Generated by Django 6.0.2 on 2026-07-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='paiements/'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'قيد المراجعة'), ('valide', 'مقبول'), ('rejete', 'مرفوض')], default='en_attente', max_length=20),
        ),
    ]
