# Generated by Django 6.0.2 on 2026-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_reco_optionnel_et_date_validation_reelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('coordonnees', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
