# Generated by Django 6.0.2 on 2026-08-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_seed_moyen_paiement_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenpaiement',
            name='coordonnees_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='coordonnees_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='label_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
