# Generated by Django 6.0.2 on 2026-09-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_documenteleve_titre_en_documenteleve_titre_fr_and_more'),
        ('payments', '0005_moyenpaiement_coordonnees_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_echeance', models.DateField()),
                ('date_fin_couverte', models.DateField(blank=True, null=True)),
                ('date_reglement', models.DateField(blank=True, null=True)),
                ('montant_regle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regle', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_abonnement', to='accounts.eleve')),
            ],
            options={
                'verbose_name': "Cycle d'abonnement",
                'verbose_name_plural': "Cycles d'abonnement",
                'ordering': ['eleve', 'numero'],
                'unique_together': {('eleve', 'numero')},
            },
        ),
    ]
