# Generated by Django 6.0.2 on 2026-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_documenteleve_titre_en_documenteleve_titre_fr_and_more'),
        ('payments', '0007_backfill_cycles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cycleabonnement',
            index=models.Index(fields=['regle', 'date_echeance'], name='cycle_abo_retard_idx'),
        ),
    ]
