# Generated by Django 6.0.2 on 2026-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_recalage_cycles_roulants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nb_mois_couverts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
