# Generated by Django 6.0.2 on 2026-09-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paiement_nb_mois_couverts'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='soumis_par_eleve',
            field=models.BooleanField(default=True),
        ),
    ]
