# Generated by Django 6.0.2 on 2026-03-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('ville', models.CharField(max_length=100)),
                ('statut_familial', models.CharField(max_length=50)),
                ('job_actuel', models.CharField(max_length=100)),
                ('certifications', models.TextField()),
                ('niveau_memorisation', models.CharField(max_length=100)),
                ('type_eleve_preference', models.JSONField(default=list)),
                ('contrainte_genre', models.JSONField(default=list)),
                ('langues', models.JSONField(default=list)),
                ('outils_maitrises', models.JSONField(default=list)),
                ('parcours_scolaire', models.TextField()),
                ('parcours_enseignant', models.TextField()),
                ('compte_bancaire', models.CharField(max_length=50)),
                ('rib', models.CharField(max_length=50)),
                ('audio_enregistrement', models.FileField(blank=True, null=True, upload_to='audio_inscriptions/')),
                ('gestion_eleve_faible', models.TextField()),
                ('gestion_eleve_absent', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription Professeur',
                'verbose_name_plural': 'Inscriptions Professeurs',
            },
        ),
        migrations.CreateModel(
            name='InscriptionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom_parent', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('programme', models.CharField(choices=[('hifz', 'الحفظ والمراجعة وتعلم أحكام التجويد'), ('tathbit', 'التثبيت وتعلم أحكام التجويد')], max_length=20)),
                ('riwaya', models.CharField(choices=[('warsh', 'ورش'), ('hafs', 'حفص')], max_length=10)),
                ('outil', models.CharField(choices=[('whatsapp', 'واتساب'), ('meet', 'Google Meet'), ('les_deux', 'كلاهما')], max_length=20)),
                ('abonnement', models.CharField(choices=[('groupe_1mois', 'جماعي - شهر (80 درهم)'), ('groupe_3mois', 'جماعي - 3 أشهر (220 درهم)'), ('individuel_1mois', 'فردي - شهر (400 درهم)'), ('individuel_3mois', 'فردي - 3 أشهر (1100 درهم)')], max_length=30)),
                ('accepte_conditions', models.BooleanField(default=False)),
                ('veut_contribuer', models.BooleanField(default=False)),
                ('remarques', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('creneau_souhaite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='courses.creneau')),
            ],
            options={
                'verbose_name': 'Inscription Élève',
                'verbose_name_plural': 'Inscriptions Élèves',
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lun', 'Lundi'), ('mar', 'Mardi'), ('mer', 'Mercredi'), ('jeu', 'Jeudi'), ('ven', 'Vendredi'), ('sam', 'Samedi'), ('dim', 'Dimanche')], max_length=10)),
                ('heure', models.CharField(choices=[('07h', '07:00'), ('09h', '09:00'), ('11h', '11:00'), ('13h', '13:00'), ('15h', '15:00'), ('17h', '17:00'), ('19h', '19:00'), ('21h', '21:00')], max_length=5)),
                ('inscription_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='inscriptions.inscriptionprof')),
            ],
            options={
                'verbose_name': 'Disponibilité Inscription',
                'unique_together': {('inscription_prof', 'jour', 'heure')},
            },
        ),
    ]
