# Generated by Django 6.0.2 on 2026-07-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='disponibilites_libres',
            field=models.TextField(blank=True, help_text="Rempli par l'élève quand aucun créneau actif ne correspond à son profil (âge/sexe)."),
        ),
    ]
