# Generated by Django 6.0.2 on 2026-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_inscriptioneleve_disponibilites_libres'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Type d'abonnement",
                'verbose_name_plural': "Types d'abonnement",
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterField(
            model_name='inscriptioneleve',
            name='abonnement',
            field=models.CharField(max_length=30),
        ),
    ]
