# Generated by Django 6.0.2 on 2026-07-04 17:47

from django.db import migrations

TARIFS_INITIAUX = [
    ('groupe_1mois', 'جماعي - شهر', 80, 1),
    ('groupe_3mois', 'جماعي - 3 أشهر', 220, 2),
    ('individuel_1mois', 'فردي - شهر', 400, 3),
    ('individuel_3mois', 'فردي - 3 أشهر', 1100, 4),
]


def creer_tarifs_initiaux(apps, schema_editor):
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    for code, label, prix, ordre in TARIFS_INITIAUX:
        TypeAbonnement.objects.get_or_create(
            code=code,
            defaults={'label': label, 'prix': prix, 'ordre': ordre},
        )


def supprimer_tarifs_initiaux(apps, schema_editor):
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    TypeAbonnement.objects.filter(code__in=[c for c, *_ in TARIFS_INITIAUX]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_typeabonnement_alter_inscriptioneleve_abonnement'),
    ]

    operations = [
        migrations.RunPython(creer_tarifs_initiaux, supprimer_tarifs_initiaux),
    ]
