# Generated by Django 6.0.2 on 2026-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_seed_types_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionprof',
            name='disponibilites',
            field=models.JSONField(default=list, help_text="Stockage temporaire de la matrice de disponibilités saisie à la candidature (ex: ['lun_14:00', 'mar_15:00']), copiée vers DisponibiliteProf à la validation."),
        ),
        migrations.DeleteModel(
            name='DisponibiliteInscription',
        ),
    ]
