# Generated by Django 6.0.2 on 2026-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_inscriptionprof_disponibilites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='disponibilites',
            field=models.JSONField(default=list, help_text="Stockage temporaire de la matrice de disponibilités saisie à la candidature (ex: ['lun_14:00', 'mar_15:00']), copiée vers DisponibiliteEleve à la validation."),
        ),
    ]
