# Generated by Django 6.0.2 on 2026-07-16 16:31

from django.db import migrations, models


def marquer_types_individuels(apps, schema_editor):
    """Le champ vient d'être ajouté avec default='groupe' pour toutes les lignes
    existantes — corrige les types dont le code suit la convention 'individuel_*'
    (voir 0004_seed_types_abonnement.py)."""
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    TypeAbonnement.objects.filter(code__startswith='individuel').update(type_offre='individuel')


def restaurer_type_groupe(apps, schema_editor):
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    TypeAbonnement.objects.filter(code__startswith='individuel').update(type_offre='groupe')


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_inscriptioneleve_disponibilites'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeabonnement',
            name='type_offre',
            field=models.CharField(choices=[('groupe', 'جماعي'), ('individuel', 'فردي')], default='groupe', max_length=10),
        ),
        migrations.RunPython(marquer_types_individuels, restaurer_type_groupe),
    ]
