# Generated by Django 6.0.2 on 2026-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0007_typeabonnement_type_offre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionprof',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee_directeur', 'Validée par le directeur — en attente du المشرف'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
