# Generated by Django 6.0.2 on 2026-07-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_alter_inscriptionprof_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionprof',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
