# Generated by Django 6.0.2 on 2026-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_ajouter_telephone_inscriptionprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioneleve',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('valide', 'مقبول'), ('rejete', 'مرفوض')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscriptionprof',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('validee_directeur', 'مقبول من المدير — بانتظار تصديق المشرف'), ('valide', 'مقبول نهائياً'), ('rejete', 'مرفوض')], default='en_attente', max_length=20),
        ),
    ]
