# Generated by Django 6.0.2 on 2026-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0010_arabiser_libelles_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeabonnement',
            name='cible_age',
            field=models.CharField(choices=[('enfant', 'أطفال'), ('adulte', 'بالغون'), ('les_deux', 'الجميع')], default='les_deux', max_length=10),
        ),
    ]
