# Generated by Django 6.0.2 on 2026-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0011_typeabonnement_cible_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionprof',
            name='agence_bancaire',
            # default='' uniquement pour peupler les lignes existantes (candidatures déjà
            # soumises avant l'ajout du champ) — le formulaire d'inscription (inscriptions.views.
            # inscription_prof) impose déjà ce champ comme obligatoire pour toute NOUVELLE
            # candidature, même principe que compte_bancaire/rib.
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
