# Generated by Django 6.0.2 on 2026-08-03 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0012_inscriptionprof_agence_bancaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresInscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouverte_eleve_adulte', models.BooleanField(default=True)),
                ('ouverte_eleve_enfant', models.BooleanField(default=True)),
                ('ouverte_prof', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_modification_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paramètres d'inscription",
                'verbose_name_plural': "Paramètres d'inscription",
            },
        ),
    ]
