# Generated by Django 6.0.2 on 2026-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0013_parametresinscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='job_actuel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
