# Generated by Django 6.0.2 on 2026-08-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0014_inscriptioneleve_job_actuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptioneleve',
            name='job_actuel',
        ),
    ]
