# Generated by Django 6.0.2 on 2026-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0015_remove_inscriptioneleve_job_actuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='job_actuel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
