# Generated by Django 6.0.2 on 2026-08-13 23:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_groupe_courses_groupe_nom_trgm'),
        ('inscriptions', '0016_inscriptioneleve_job_actuel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscriptioneleve',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_parent'], name='inscriptions_ins_parent_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
