# Generated by Django 6.0.2 on 2026-08-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0017_inscriptioneleve_inscriptions_ins_parent_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseRefus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexte', models.CharField(choices=[('refus_eleve', 'رفض طلب طالب (المدير)'), ('refus_prof_etape1', 'رفض طلب أستاذ - المرحلة الأولى (المدير)'), ('refus_prof_etape2', 'رفض طلب أستاذ - المرحلة الثانية (المشرف)')], max_length=30)),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phrase de refus',
                'verbose_name_plural': 'Phrases de refus',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='inscriptioneleve',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscriptionprof',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
    ]
