# Generated by Django 6.0.2 on 2026-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0018_phraserefus_inscriptioneleve_motif_refus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresinscriptions',
            name='delai_contact_heures',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='parametresinscriptions',
            name='delai_paiement_jours',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
