# Generated by Django 6.0.2 on 2026-08-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_creneau_heure_debut_1_and_more'),
        ('inscriptions', '0019_parametresinscriptions_delai_contact_heures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='groupe_choisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_le_choisissant', to='courses.groupe'),
        ),
        migrations.AlterField(
            model_name='inscriptioneleve',
            name='outil',
            field=models.CharField(blank=True, choices=[('whatsapp', 'واتساب'), ('meet', 'Google Meet'), ('les_deux', 'كلاهما')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscriptioneleve',
            name='programme',
            field=models.CharField(blank=True, choices=[('hifz', 'الحفظ والمراجعة وتعلم أحكام التجويد'), ('tathbit', 'التثبيت وتعلم أحكام التجويد')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscriptioneleve',
            name='riwaya',
            field=models.CharField(blank=True, choices=[('warsh', 'ورش'), ('hafs', 'حفص')], default='', max_length=10),
        ),
    ]
