# Generated by Django 6.0.2 on 2026-08-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0021_inscriptioneleve_cree_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrillePrixAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_slots', models.PositiveSmallIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('est_actif', models.BooleanField(default=True)),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grille_prix', to='inscriptions.typeabonnement')),
            ],
            options={
                'verbose_name': 'Prix de grille (abonnement × nb séances)',
                'verbose_name_plural': 'Grille de prix des abonnements',
                'ordering': ['type_abonnement__ordre', 'nb_slots'],
                'unique_together': {('type_abonnement', 'nb_slots')},
            },
        ),
    ]
