# Generated by Django 6.0.2 on 2026-08-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0022_grilleprixabonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='niveau_scolaire',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
