# Generated by Django 6.0.2 on 2026-08-22 18:48

from django.db import migrations, models

# Mêmes 4 codes/durées que la seed initiale (0004_seed_types_abonnement) —
# jamais devinés, la même vérité que celle déjà écrite là-bas.
DUREES_CONNUES = {
    'groupe_1mois': 'شهر',
    'groupe_3mois': '3 أشهر',
    'individuel_1mois': 'شهر',
    'individuel_3mois': '3 أشهر',
}


def remplir_duree(apps, schema_editor):
    """Correction 5 (2026-08-22, chantier grille de prix) : `duree` est un
    champ à part, jamais dérivé de `label` par un découpage de texte
    fragile en code (voir TypeAbonnement.duree_affichee) — mais ce
    backfill UNIQUE, ici, doit bien lire les `label` déjà en base pour ne
    pas laisser `duree` vide sur des abonnements réels existants
    (client réel, voir CLAUDE.md).

    1) Codes seedés par 0004 : durée exacte connue (DUREES_CONNUES),
       jamais une supposition.
    2) Toute AUTRE ligne (créée depuis via l'admin, y compris en
       production) : `label` suit encore la même convention "TYPE - DURÉE"
       (seule convention utilisée par admin_abonnement_ajouter jusqu'ici)
       -> on prend tout ce qui suit le DERNIER " - " comme durée.
    3) Si ce découpage ne trouve rien (label sans " - ") : `duree` reste
       vide, TypeAbonnement.duree_affichee retombe alors sur `label` en
       entier — jamais un texte tronqué à tort, jamais un plantage.

    Ne touche QUE les lignes où `duree` est encore vide — un مدير qui
    aurait déjà rempli ce champ (impossible avant cette migration, mais
    principe systématique de ce projet) ne serait jamais écrasé."""
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    for abonnement in TypeAbonnement.objects.filter(duree=''):
        if abonnement.code in DUREES_CONNUES:
            abonnement.duree = DUREES_CONNUES[abonnement.code]
        elif ' - ' in abonnement.label:
            abonnement.duree = abonnement.label.rsplit(' - ', 1)[-1].strip()
        else:
            continue
        abonnement.save(update_fields=['duree'])


def vider_duree(apps, schema_editor):
    # Best-effort, ne revient que sur les 4 codes seedés connus avec
    # certitude — les lignes heuristiquement déduites (2) ne sont pas
    # distinguables après coup d'une valeur qu'un مدير aurait saisie
    # entre-temps, même principe que la réversibilité "best-effort" déjà
    # utilisée pour la migration 0006 (message_aucun_groupe_exact).
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    TypeAbonnement.objects.filter(code__in=DUREES_CONNUES.keys()).update(duree='')


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0023_inscriptioneleve_niveau_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeabonnement',
            name='duree',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(remplir_duree, vider_duree),
    ]
