# Generated by Django 6.0.2 on 2026-08-22

from django.db import migrations

# Mêmes libellés que TypeAbonnement.TYPE_OFFRE_CHOICES (jamais dupliqués
# ailleurs que là où c'est nécessaire pour une migration historique, qui ne
# peut pas importer le modèle réel).
PREFIXES = ['جماعي - ', 'فردي - ']


def retirer_prefixe(apps, schema_editor):
    """Correction 4 (2026-08-22, suite au test local du dashboard مدير) : le
    type d'offre (جماعي/فردي) est déjà visible ailleurs (section dédiée de
    la page مدير, voir correction 5 du même cycle ; badge du type d'offre
    déjà affiché à l'étape précédente du wizard public, voir correction 5
    du cycle précédent pour `duree`) — le répéter DANS `label` lui-même est
    la même redondance que celle déjà corrigée pour `duree`, mais ici sur
    la DONNÉE stockée, pas seulement l'affichage à un endroit précis.

    Contrairement à `duree` (backfill non destructif d'un champ vide),
    ceci MODIFIE `label` en place — mais seulement pour retirer un préfixe
    reconnu avec certitude (jamais un texte deviné), et seulement s'il est
    suivi d'autre chose (un label ÉGAL au préfixe seul, ex: "جماعي -" sans
    rien après, n'est jamais vidé)."""
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    for abonnement in TypeAbonnement.objects.all():
        for prefixe in PREFIXES:
            if abonnement.label.startswith(prefixe) and len(abonnement.label) > len(prefixe):
                abonnement.label = abonnement.label[len(prefixe):]
                abonnement.save(update_fields=['label'])
                break


def rajouter_prefixe(apps, schema_editor):
    """Best-effort (même principe que la réversibilité de 0006/0024) : ne
    revient que sur les lignes dont le label ne contient encore AUCUN " - "
    (signe qu'il n'a pas été modifié entre-temps par le مدير) — re-préfixe
    depuis le type_offre actuel de la ligne, seule information encore fiable
    à ce stade."""
    TypeAbonnement = apps.get_model('inscriptions', 'TypeAbonnement')
    PREFIXE_PAR_OFFRE = {'groupe': 'جماعي - ', 'individuel': 'فردي - '}
    for abonnement in TypeAbonnement.objects.all():
        if ' - ' in abonnement.label:
            continue
        prefixe = PREFIXE_PAR_OFFRE.get(abonnement.type_offre)
        if prefixe:
            abonnement.label = prefixe + abonnement.label
            abonnement.save(update_fields=['label'])


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0024_typeabonnement_duree'),
    ]

    operations = [
        migrations.RunPython(retirer_prefixe, rajouter_prefixe),
    ]
