# Generated by Django 6.0.2 on 2026-08-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0025_nettoyer_prefixe_label_type_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='nombre_mois_payes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
