# Generated by Django 6.0.2 on 2026-08-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0026_inscriptioneleve_nombre_mois_payes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptioneleve',
            name='nombre_mois_payes',
        ),
    ]
