# Generated by Django 6.0.2 on 2026-08-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0027_retirer_nombre_mois_payes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeabonnement',
            name='duree',
            field=models.CharField(blank=True, choices=[('1mois', 'شهر واحد'), ('3mois', '3 أشهر'), ('6mois', '6 أشهر'), ('1an', 'سنة واحدة')], default='', max_length=50),
        ),
    ]
