# Generated by Django 6.0.2 on 2026-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0030_seed_grille_prix_besoin2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionprof',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
