# Generated by Django 6.0.2 on 2026-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0031_inscriptionprof_date_naissance_optionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionprof',
            name='date_validee_directeur',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
