# Generated by Django 6.0.2 on 2026-08-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0033_backfill_date_validee_directeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionprof',
            name='charte_acceptee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptionprof',
            name='date_acceptation_charte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
