# Generated by Django 6.0.2 on 2026-08-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0034_inscriptionprof_charte_acceptee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeabonnement',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='typeabonnement',
            name='label_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
