# Generated by Django 6.0.2 on 2026-09-06 15:45
#
# Demande du client (2026-09-06) : l'enfant qui s'inscrit en séances
# INDIVIDUELLES indique le sexe de l'enseignant qu'il souhaite. Champ
# purement indicatif pour la direction (aucun filtrage, aucune règle
# bloquante). Vide ('') pour toute candidature existante et pour tout autre
# parcours (adulte, groupe, ajout manuel, ancien formulaire) — AddField avec
# default='' suffit, pas de backfill.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0036_parametres_relance_paiement_quotidienne'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioneleve',
            name='sexe_prof_souhaite',
            field=models.CharField(blank=True, choices=[('homme', 'أستاذ'), ('femme', 'أستاذة')], default='', max_length=10),
        ),
    ]
