# Generated by Django 6.0.2 on 2026-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0037_inscriptioneleve_sexe_prof_souhaite'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionprof',
            name='date_traitee_mshrif',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscriptionprof',
            name='mot_de_passe_genere',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
