# Generated by Django 6.0.2 on 2026-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='annonces_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='nom_fichier_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annonce',
            name='taille_fichier_octets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type_fichier',
            field=models.CharField(blank=True, choices=[('image', 'صورة'), ('video', 'فيديو'), ('audio', 'ملف صوتي'), ('document', 'مستند')], default='', max_length=10),
        ),
    ]
