# Generated by Django 6.0.2 on 2026-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_fichier_annonce_nom_fichier_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='cible',
            field=models.CharField(choices=[('femmes_adultes', 'الطالبات البالغات'), ('hommes_adultes', 'الطلاب البالغون'), ('mineurs', 'الأطفال')], max_length=20),
        ),
    ]
