# Generated by Django 6.0.2 on 2026-08-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_annonce_cible'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='tranche_age',
            field=models.CharField(blank=True, choices=[('talqin', 'التلقين'), ('baraim', 'البراعم'), ('yafiun', 'اليافعون')], default='', max_length=10),
        ),
    ]
