# Generated by Django 6.0.2 on 2026-08-15 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0027_groupe_courses_groupe_nom_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_retention_jours', models.PositiveIntegerField(default=7)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_modification_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration du chat',
                'verbose_name_plural': 'Configuration du chat',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='courses.groupe')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='LectureConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_lecture', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture de conversation',
                'verbose_name_plural': 'Lectures de conversation',
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(blank=True, default='', max_length=150)),
                ('auteur_role', models.CharField(blank=True, default='', max_length=20)),
                ('type_message', models.CharField(choices=[('texte', 'نص'), ('audio', 'رسالة صوتية'), ('fichier', 'ملف مرفق')], default='texte', max_length=10)),
                ('contenu', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/')),
                ('nom_fichier_original', models.CharField(blank=True, default='', max_length=255)),
                ('taille_fichier_octets', models.PositiveIntegerField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date_envoi'],
                'indexes': [models.Index(fields=['conversation', 'date_envoi'], name='chat_msg_conv_date_idx'), models.Index(fields=['date_envoi'], name='chat_msg_date_idx')],
            },
        ),
    ]
