# Generated by Django 6.0.2 on 2026-08-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_backfill_conversations_existantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
