# Generated by Django 6.0.2 on 2026-08-27 14:43

import chat.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_est_supprime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=chat.storage.storage_pieces_jointes_chat, upload_to='chat_attachments/%Y/%m/'),
        ),
    ]
