# Generated by Django 6.0.2 on 2026-03-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='gestion_eleve_absent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='gestion_eleve_faible',
            field=models.TextField(blank=True),
        ),
    ]
