# Generated by Django 6.0.2 on 2026-07-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prof_gestion_eleve_absent_prof_gestion_eleve_faible'),
        ('inscriptions', '0002_inscriptioneleve_disponibilites_libres'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleve_valide', to='inscriptions.inscriptioneleve'),
        ),
        migrations.AddField(
            model_name='prof',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_valide', to='inscriptions.inscriptionprof'),
        ),
    ]
