# Generated by Django 6.0.2 on 2026-07-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_eleve_inscription_prof_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='superviseur',
            name='profs_assignes',
            field=models.ManyToManyField(blank=True, related_name='superviseurs', to='accounts.prof'),
        ),
    ]
