# Generated by Django 6.0.2 on 2026-07-16 17:36

from django.db import migrations, models


def ne_pas_bloquer_les_comptes_existants(apps, schema_editor):
    """Le champ vient d'être ajouté avec default=True pour tous les comptes
    existants — sans ce backfill, TOUS les comptes déjà en usage (y compris
    l'admin) seraient bloqués sur le changement de mot de passe forcé dès
    leur prochaine requête. Seuls les comptes créés à partir de maintenant
    doivent passer par ce changement obligatoire."""
    User = apps.get_model('accounts', 'User')
    User.objects.update(doit_changer_mot_de_passe=False)


def restaurer_true_pour_tous(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.update(doit_changer_mot_de_passe=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assigner_profs_aux_superviseurs_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(ne_pas_bloquer_les_comptes_existants, restaurer_true_pour_tous),
    ]
