# Generated by Django 6.0.2 on 2026-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('actif', 'نشط'), ('suspendu', 'موقوف'), ('ancien', 'قديم'), ('nouveau', 'جديد')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'طالب'), ('prof', 'معلم'), ('superviseur', 'مشرف'), ('admin', 'مدير')], default='eleve', max_length=20),
        ),
    ]
