# Generated by Django 6.0.2 on 2026-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_eleve_statut_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='majoration_mensuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
