# Generated by Django 6.0.2 on 2026-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prof_majoration_mensuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'طالب'), ('prof', 'معلم'), ('superviseur', 'مؤطر'), ('admin', 'مدير'), ('mshrif', 'المشرف')], default='eleve', max_length=20),
        ),
    ]
