# Generated by Django 6.0.2 on 2026-07-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Charte d'enseignement",
                'verbose_name_plural': "Charte d'enseignement",
            },
        ),
        migrations.AddField(
            model_name='prof',
            name='charte_acceptee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prof',
            name='date_acceptation_charte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
