# Generated by Django 6.0.2 on 2026-07-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_charte_enseignement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charteenseignement',
            name='contenu',
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section1_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section1_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section1_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section2_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section2_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section2_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section3_conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section3_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section3_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section3_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section4_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section4_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section4_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section5_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section5_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section5_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section6_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section6_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section6_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section7_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section7_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='section7_titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='titre_bunud',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='verset_ouverture',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='verset_rahma_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='charteenseignement',
            name='verset_rahma_texte',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CharteSanctionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('violation', models.CharField(max_length=300)),
                ('severite', models.CharField(choices=[('immediate', 'الإعفاء الفوري'), ('progressive', 'إنذار أول ← إنذار ثاني ← خصم من الراتب')], default='progressive', max_length=20)),
                ('charte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='accounts.charteenseignement')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
