# Generated by Django 6.0.2 on 2026-07-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_migrer_charte_vers_champs_structures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme général',
                'verbose_name_plural': 'Programme général',
            },
        ),
    ]
