# Generated by Django 6.0.2 on 2026-07-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_programmegeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo de la plateforme',
                'verbose_name_plural': 'Logo de la plateforme',
            },
        ),
    ]
