# Generated by Django 6.0.2 on 2026-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_logoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_suspension',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('actif', 'نشط'), ('suspendu', 'موقوف'), ('archive', 'مؤرشف')], default='actif', max_length=20),
        ),
    ]
