# Generated by Django 6.0.2 on 2026-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_eleve_statut_archive_et_date_suspension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmegeneral',
            name='contenu',
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='intro_adultes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='intro_enfants',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='items_adultes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='items_enfants',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='titre_adultes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='titre_enfants',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
