# Generated by Django 6.0.2 on 2026-07-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_reseed_charte_et_programme_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description_courte',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
