# Generated by Django 6.0.2 on 2026-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_description_courte'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='date_debut_effectif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='notes_admin',
            field=models.TextField(blank=True, default=''),
        ),
    ]
