# Generated by Django 6.0.2 on 2026-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_prof_date_debut_effectif_prof_notes_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='agence_bancaire',
            # default='' uniquement pour peupler les Prof déjà validés avant l'ajout du champ
            # (leur InscriptionProf d'origine n'a pas cette info). Nouveaux Prof: toujours
            # copié depuis InscriptionProf.agence_bancaire à la validation (mshrif_valider_prof_final),
            # jamais vide — même principe que compte_bancaire/rib.
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
