# Generated by Django 6.0.2 on 2026-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_prof_agence_bancaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='statut',
            field=models.CharField(choices=[('actif', 'نشط'), ('archive', 'مؤرشف')], default='actif', max_length=20),
        ),
    ]
