# Generated by Django 6.0.2 on 2026-08-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_prof_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibiliteProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afficher_ville', models.BooleanField(default=True)),
                ('afficher_certifications', models.BooleanField(default=True)),
                ('afficher_niveau_memorisation', models.BooleanField(default=True)),
                ('afficher_type_eleve_preference', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visibilité du profil professeur (élève)',
                'verbose_name_plural': 'Visibilité du profil professeur (élève)',
            },
        ),
    ]
