# Generated by Django 6.0.2 on 2026-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_visibiliteprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_langues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_outils_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_parcours_educatif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_parcours_scolaire',
            field=models.BooleanField(default=False),
        ),
    ]
