# Generated by Django 6.0.2 on 2026-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_visibiliteprof_afficher_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='job_actuel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_travail_actuel',
            field=models.BooleanField(default=False),
        ),
    ]
