# Generated by Django 6.0.2 on 2026-08-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_prof_job_actuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementHakiba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(choices=[('texte', 'نص'), ('fichier', 'ملف'), ('video', 'فيديو')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('contenu_texte', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='hakiba_prof/')),
                ('lien_video', models.URLField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_hakiba', to='accounts.prof')),
            ],
            options={
                'verbose_name': 'Élément de حقيبة الأستاذ',
                'verbose_name_plural': 'Éléments de حقيبة الأستاذ',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
