# Generated by Django 6.0.2 on 2026-08-05 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_elementhakiba'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_reinitialisation_mot_de_passe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mot_de_passe_reinitialise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
