# Generated by Django 6.0.2 on 2026-08-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_date_reinitialisation_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurMotDePasseSequentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compteur de mot de passe séquentiel',
                'verbose_name_plural': 'Compteur de mot de passe séquentiel',
            },
        ),
    ]
