# Generated by Django 6.0.2 on 2026-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_compteurmotdepassesequentiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementhakiba',
            name='lien_video',
        ),
        migrations.RemoveField(
            model_name='elementhakiba',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='elementhakiba',
            name='type_element',
        ),
        migrations.AddField(
            model_name='elementhakiba',
            name='profs_cibles',
            field=models.ManyToManyField(blank=True, related_name='elements_hakiba', to='accounts.prof'),
        ),
        migrations.AddField(
            model_name='elementhakiba',
            name='tous_les_profs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='elementhakiba',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
