# Generated by Django 6.0.2 on 2026-08-13 23:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_activer_pg_trgm'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inscriptions', '0016_inscriptioneleve_job_actuel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='prof',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ville'], name='accounts_prof_ville_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='accounts_user_fn_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='accounts_user_ln_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='accounts_user_email_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['telephone'], name='accounts_user_tel_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
