# Generated by Django 6.0.2 on 2026-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_options_prof_accounts_prof_ville_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'طالب'), ('prof', 'معلم'), ('superviseur', 'مؤطر'), ('admin', 'الإدارة'), ('mshrif', 'المشرف')], default='eleve', max_length=20),
        ),
    ]
