# Generated by Django 6.0.2 on 2026-08-18 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePersonnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_personnelles_ecrites', to=settings.AUTH_USER_MODEL)),
                ('profil_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_personnelles_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note personnelle',
                'verbose_name_plural': 'Notes personnelles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
