# Generated by Django 6.0.2 on 2026-08-18 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_notepersonnelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('fichier', models.FileField(upload_to='cartable_eleve/%Y/%m/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_cartable', to='accounts.eleve')),
            ],
            options={
                'verbose_name': 'Document du cartable élève',
                'verbose_name_plural': 'Documents du cartable élève',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
