# Generated by Django 6.0.2 on 2026-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_documenteleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepersonnelle',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
