# Generated by Django 6.0.2 on 2026-08-19 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_notepersonnelle_titre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superviseur',
            options={'verbose_name': 'Superviseur'},
        ),
        migrations.CreateModel(
            name='DerniereVisiteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=30)),
                ('date_visite', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dernieres_visites_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dernière visite de notification',
                'verbose_name_plural': 'Dernières visites de notification',
                'unique_together': {('user', 'cle')},
            },
        ),
    ]
