# Generated by Django 6.0.2 on 2026-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_seed_dernieres_visites_notification_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='presentation_publique',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visibiliteprof',
            name='afficher_presentation_wizard',
            field=models.BooleanField(default=True),
        ),
    ]
