# Generated by Django 6.0.2 on 2026-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_prof_presentation_publique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charteenseignement',
            name='traductions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chartesanctionligne',
            name='violation_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='chartesanctionligne',
            name='violation_fr',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
