# Generated by Django 6.0.2 on 2026-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_charteenseignement_traductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='presentation_publique_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prof',
            name='presentation_publique_fr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
