# Generated by Django 6.0.2 on 2026-08-30 16:16, réordonné et complété à la
# main (RunPython) — refonte du cartable élève en ciblage dynamique (voir
# accounts.models.DocumentEleve.__doc__). L'auto-génération de Django
# proposait de SUPPRIMER le champ `eleve` avant d'ajouter `eleves_cibles`,
# ce qui aurait perdu l'affectation de chaque document déjà en base (données
# réelles d'un client en production). Ordre corrigé : on ajoute d'abord les
# nouveaux champs, on copie eleve -> eleves_cibles (mode 'specifique',
# comportement inchangé pour l'existant — décision confirmée), PUIS on
# supprime l'ancien champ eleve.

from django.db import migrations, models


def _copier_eleve_vers_eleves_cibles(apps, schema_editor):
    DocumentEleve = apps.get_model('accounts', 'DocumentEleve')
    for doc in DocumentEleve.objects.all():
        doc.cible_type = 'specifique'
        doc.eleves_cibles.add(doc.eleve_id)
        doc.save(update_fields=['cible_type'])


def _rien_a_defaire(apps, schema_editor):
    # Pas de retour arrière utile : la suppression du champ `eleve` (opération
    # suivante) rend cette copie non réversible proprement. Un rollback complet
    # de cette migration recrée `eleve` vide (SET_NULL n'a pas de valeur à
    # restaurer) — cohérent avec le reste du projet (voir migrations similaires).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_prof_presentation_publique_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenteleve',
            name='categorie_cible',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='documenteleve',
            name='cible_type',
            field=models.CharField(choices=[('tous', 'كل الطلاب'), ('categorie', 'فئة معينة'), ('specifique', 'طلاب محددون')], default='specifique', max_length=20),
        ),
        migrations.AddField(
            model_name='documenteleve',
            name='eleves_cibles',
            field=models.ManyToManyField(blank=True, related_name='documents_cartable_cibles', to='accounts.eleve'),
        ),
        migrations.RunPython(_copier_eleve_vers_eleves_cibles, _rien_a_defaire),
        migrations.RemoveField(
            model_name='documenteleve',
            name='eleve',
        ),
    ]
