# Generated by Django 6.0.2 on 2026-08-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_seed_dernieres_visites_notification_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmegeneral',
            name='intro_adultes_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='intro_adultes_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='intro_enfants_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='intro_enfants_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='items_adultes_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='items_adultes_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='items_enfants_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='items_enfants_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='titre_adultes_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='titre_adultes_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='titre_enfants_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programmegeneral',
            name='titre_enfants_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
