# Generated by Django 6.0.2 on 2026-08-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_programmegeneral_intro_adultes_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenteleve',
            name='titre_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='documenteleve',
            name='titre_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='elementhakiba',
            name='contenu_texte_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='elementhakiba',
            name='contenu_texte_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='elementhakiba',
            name='titre_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='elementhakiba',
            name='titre_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
