# Generated by Django 6.0.2 on 2026-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_documenteleve_titre_en_documenteleve_titre_fr_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_user_email_btree'),
        ),
    ]
