# Generated by Django 6.0.2 on 2026-09-04 22:40
# Renumérotée 0048 -> 0049 le 2026-09-06 : collision avec
# 0048_seed_dernieres_visites_notification_paiements (poussé sur main
# entre-temps par le lot « fusion horaire »). Dépendance recâblée sur 0048.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_seed_dernieres_visites_notification_paiements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeGeneralParSeances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('enfant', 'طفل'), ('adulte', 'بالغ')], max_length=10)),
                ('nb_slots', models.PositiveSmallIntegerField()),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('items', models.TextField(blank=True)),
                ('titre_fr', models.CharField(blank=True, default='', max_length=200)),
                ('titre_en', models.CharField(blank=True, default='', max_length=200)),
                ('intro_fr', models.TextField(blank=True, default='')),
                ('intro_en', models.TextField(blank=True, default='')),
                ('items_fr', models.TextField(blank=True, default='')),
                ('items_en', models.TextField(blank=True, default='')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme général (par nombre de séances)',
                'verbose_name_plural': 'Programme général (par nombre de séances)',
                'ordering': ['tranche_age', 'nb_slots'],
                'unique_together': {('tranche_age', 'nb_slots')},
            },
        ),
    ]
