"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'accounts.User'

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)
AUTHENTICATION_BACKENDS = ['accounts.backend.EmailBackend']
LOGIN_URL = '/accounts/login/'
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

# Manquait entièrement (Tâche du 2026-08-07 — bug réel : "Bad Request (400)"
# sur le nouveau sous-domaine app.zidanieilman.com, ALLOWED_HOSTS pas encore
# à jour côté Render). Django n'a pas besoin de CSRF_TRUSTED_ORIGINS pour
# qu'un domaine dans ALLOWED_HOSTS fonctionne en lecture, mais l'exige pour
# les soumissions de formulaire (POST) une fois servi derrière le proxy
# HTTPS de Render — même patron env.list que ALLOWED_HOSTS, mais avec le
# schéma complet (https://...), pas juste le nom d'hôte.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Bug signalé le 2026-08-24 : la page 403 par défaut de Django (technique,
# en anglais) s'affichait sans aucune explication ni moyen de continuer
# quand une vérification CSRF légitime échoue (ex: formulaire du wizard
# public resté ouvert longtemps dans un onglet avant d'être soumis — voir
# core.views.csrf_failure.__doc__ pour le diagnostic complet, aucun bug de
# code trouvé après revérification complète du parcours avec
# Client(enforce_csrf_checks=True)). Remplacée par une page arabe RTL
# cohérente avec le reste du site, qui recharge la même page en un clic.
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'

# Render place le service derrière un proxy HTTPS : la requête arrive en HTTP
# en interne avec un header indiquant le protocole d'origine.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'cloudinary_storage',
    'cloudinary',
    'accounts',
    'inscriptions',
    'courses',
    'payments',
    'evaluations',
    'dashboard',
    'chat',
    'annonces',
    'examens',
    'registration',
    'telegram_bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # LocaleMiddleware DOIT venir après SessionMiddleware (lit la langue en
    # session) et avant CommonMiddleware (qui s'en sert déjà pour certaines
    # redirections) — ordre documenté par Django. Active {% trans %} côté
    # requête : détecte la langue via session -> cookie -> Accept-Language du
    # navigateur -> LANGUAGE_CODE par défaut (voir set_language, core/urls.py).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # ForcerChangementMotDePasseMiddleware DOIT venir après MessageMiddleware
    # (Tâche du 2026-08-06) : depuis qu'elle appelle messages.warning() en cas
    # de blocage, elle a besoin de request._messages déjà posé par
    # MessageMiddleware — sinon AttributeError/MessageFailure à chaque
    # redirection (bug réel, trouvé par test, pas seulement en théorie).
    'accounts.middleware.ForcerChangementMotDePasseMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Fournit LANGUAGE_CODE / LANGUAGE_BIDI / LANGUAGES dans tous les
                # templates (utilisés pour dir="rtl"/"ltr" et le sélecteur de langue).
                'django.template.context_processors.i18n',
                'accounts.context_processors.logo_context',
                'chat.context_processors.chat_badge_context',
                'annonces.context_processors.annonces_badge_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Chantier traduction FR/EN (2026-08-27) — langue par défaut alignée sur le
# contenu réel du site (tout est écrit en arabe en dur dans les templates
# tant qu'aucun {% trans %} ne l'entoure). LANGUAGE_CODE ne fait QUE fournir
# le repli quand aucune langue n'est choisie (session/cookie) — ça ne traduit
# rien tout seul, il faut les balises {% trans %}/{% blocktrans %} dans les
# templates et gettext_lazy() côté Python pour que LANGUAGES ait un effet.
LANGUAGE_CODE = 'ar'

LANGUAGES = [
    ('ar', 'العربية'),
    ('fr', 'Français'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # dossier static/ du projet (logo, etc.)
STATIC_ROOT = BASE_DIR / 'staticfiles'  # rempli par collectstatic, servi par whitenoise

# Media files (fichiers uploadés par les utilisateurs, ex: audio des inscriptions prof)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Stockage des médias sur Cloudinary (survit aux redéploiements, contrairement
# au disque de Render qui est éphémère). Tant que les identifiants ne sont pas
# fournis via l'environnement, on reste sur le stockage local (dev, tests).
CLOUDINARY_CLOUD_NAME = env('CLOUDINARY_CLOUD_NAME', default='')
if CLOUDINARY_CLOUD_NAME:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': env('CLOUDINARY_API_KEY', default=''),
        'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
    }
    # RawMediaCloudinaryStorage (pas MediaCloudinaryStorage) : ce dernier suppose
    # que tout fichier est une image (resource_type='image'), ce qui casse les
    # uploads audio des candidatures prof. 'raw' accepte n'importe quel type.
    STORAGES['default'] = {'BACKEND': 'cloudinary_storage.storage.RawMediaCloudinaryStorage'}


# Email (mot de passe temporaire envoyé aux users validés)
# Par défaut: console (dev). En prod, définir EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# + EMAIL_HOST/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD (ex: identifiants SMTP Brevo) via variables d'environnement.
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@zidni-ilman.local')


# Notification Telegram au مدير/مشرف (nouvelle candidature élève/prof, paiement
# soumis, mot de passe oublié) — voir core.utils.envoyer_notification_telegram.
# Le token ne doit JAMAIS être codé en dur ni loggé : uniquement lu depuis
# l'environnement (.env local, variables d'environnement Render en production).
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
# TELEGRAM_CHAT_ID : ancien système à chat_id unique codé en dur, REMPLACÉ par
# telegram_bot.AbonneTelegram — n'importe quel مدير/مشرف autorisé s'abonne
# lui-même via /start, validé manuellement depuis le dashboard (voir
# dashboard.views.admin_telegram_abonnes). Cette variable n'est plus lue QUE
# par la migration de données telegram_bot 0002 (seed du chat_id déjà
# configuré comme 1er abonné actif, pour ne pas perdre les notifications
# existantes pendant la transition) — elle peut être retirée de l'environnement
# une fois cette migration appliquée en production, mais on la laisse ici pour
# ne rien casser tant que ce n'est pas fait.
TELEGRAM_CHAT_ID = env('TELEGRAM_CHAT_ID', default='')
# TELEGRAM_WEBHOOK_SECRET : secret arbitraire (ex: généré via `python -c
# "import secrets; print(secrets.token_urlsafe(32))"`) fourni à Telegram via
# `setWebhook` (voir telegram_bot.management.commands.set_telegram_webhook).
# Telegram le renvoie ensuite sur CHAQUE update, dans le header
# X-Telegram-Bot-Api-Secret-Token — c'est la SEULE protection du webhook
# (telegram_bot.views.webhook est forcément @csrf_exempt, Telegram n'envoyant
# aucun cookie/token CSRF Django). Sans ce secret configuré, le webhook
# rejette systématiquement toute requête (voir _secret_valide).
TELEGRAM_WEBHOOK_SECRET = env('TELEGRAM_WEBHOOK_SECRET', default='')


# Plage horaire de l'école (utilisée pour générer la grille de disponibilités des profs)
import datetime
HEURE_OUVERTURE_ECOLE = datetime.time(7, 0)
HEURE_FERMETURE_ECOLE = datetime.time(22, 0)
