# Generated by Django 6.0.2 on 2026-08-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0035_creneauslot'),
        ('inscriptions', '0019_parametresinscriptions_delai_contact_heures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('type_champ', models.CharField(choices=[('texte', 'نص'), ('email', 'بريد إلكتروني'), ('telephone', 'هاتف'), ('nombre', 'رقم'), ('date', 'تاريخ'), ('choix_unique', 'اختيار واحد'), ('choix_multiple', 'اختيار متعدد'), ('booleen', 'نعم/لا')], default='choix_unique', max_length=20)),
                ('backend', models.CharField(choices=[('eav', 'قيمة حرة (الافتراضي)'), ('champ_groupe', 'مرتبط بحقل حقيقي في نموذج المجموعة'), ('nb_slots', 'مشتق تلقائياً من عدد الحصص الأسبوعية الحقيقية')], default='eav', max_length=20)),
                ('champ_modele_groupe', models.CharField(blank=True, default='', max_length=50)),
                ('filtrable', models.BooleanField(default=False)),
                ('bloquant', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Critère d'inscription",
                'verbose_name_plural': "Critères d'inscription",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EtapeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Étape d'inscription",
                'verbose_name_plural': "Étapes d'inscription",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PresentationInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('bouton_texte', models.CharField(default='متابعة التسجيل', max_length=100)),
                ('message_bienvenue', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Présentation d'inscription",
                'verbose_name_plural': "Présentation d'inscription",
            },
        ),
        migrations.CreateModel(
            name='CritereOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='registration.critere')),
            ],
            options={
                'verbose_name': 'Option de critère',
                'verbose_name_plural': 'Options de critère',
                'ordering': ['ordre', 'id'],
                'unique_together': {('critere', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ChampInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_champ', models.CharField(blank=True, choices=[('texte', 'نص'), ('email', 'بريد إلكتروني'), ('telephone', 'هاتف'), ('nombre', 'رقم'), ('date', 'تاريخ'), ('choix_unique', 'اختيار واحد'), ('choix_multiple', 'اختيار متعدد'), ('booleen', 'نعم/لا')], default='', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('critere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='champs', to='registration.critere')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champs', to='registration.etapeinscription')),
            ],
            options={
                'verbose_name': "Champ d'inscription",
                'verbose_name_plural': "Champs d'inscription",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible_object_id', models.PositiveIntegerField()),
                ('operateur', models.CharField(choices=[('egal', 'يساوي'), ('different', 'يختلف عن'), ('dans', 'ضمن')], default='egal', max_length=20)),
                ('valeurs', models.JSONField(default=list)),
                ('est_actif', models.BooleanField(default=True)),
                ('cible_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('critere_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='registration.critere')),
            ],
            options={
                'verbose_name': 'Règle conditionnelle',
                'verbose_name_plural': 'Règles conditionnelles',
            },
        ),
        migrations.CreateModel(
            name='ReponseInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_texte', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='registration.champinscription')),
                ('critere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='registration.critere')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='inscriptions.inscriptioneleve')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='registration.critereoption')),
            ],
            options={
                'verbose_name': "Réponse d'inscription",
                'verbose_name_plural': "Réponses d'inscription",
                'ordering': ['champ__etape__ordre', 'champ__ordre'],
            },
        ),
        migrations.CreateModel(
            name='GroupeCritereValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valeurs_groupes', to='registration.critere')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_criteres', to='courses.groupe')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valeurs_groupes', to='registration.critereoption')),
            ],
            options={
                'verbose_name': 'Valeur de critère (groupe)',
                'verbose_name_plural': 'Valeurs de critère (groupes)',
                'unique_together': {('groupe', 'critere', 'option')},
            },
        ),
    ]
