# Generated by Django 6.0.2 on 2026-08-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_seed_wizard_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationChampStructurel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_cle', models.CharField(choices=[('nom', 'الاسم الكامل'), ('nom_parent', 'اسم ولي الأمر'), ('sexe', 'الجنس'), ('telephone', 'الهاتف'), ('date_naissance', 'تاريخ الميلاد'), ('email', 'البريد الإلكتروني'), ('job_actuel', 'المهنة'), ('niveau_scolaire', 'المستوى الدراسي')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('type_champ', models.CharField(blank=True, choices=[('texte', 'نص قصير'), ('texte_multiligne', 'نص طويل')], default='texte', max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=200)),
                ('texte_aide', models.CharField(blank=True, default='', max_length=300)),
                ('regex_validation', models.CharField(blank=True, default='', max_length=200)),
                ('message_erreur_regex', models.CharField(blank=True, default='', max_length=200)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champs_structurels', to='registration.etapeinscription')),
            ],
            options={
                'verbose_name': 'Configuration de champ structurel',
                'verbose_name_plural': 'Configuration des champs structurels',
                'ordering': ['etape__ordre', 'ordre', 'id'],
            },
        ),
    ]
