# Generated by Django 6.0.2 on 2026-08-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0023_inscriptioneleve_niveau_scolaire'),
        ('registration', '0004_seed_champs_structurels'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationinscription',
            name='message_aucun_groupe_exact',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DemandeNonSatisfaite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteres_json', models.JSONField(default=dict)),
                ('type_offre', models.CharField(blank=True, default='', max_length=20)),
                ('nb_slots', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, default='', max_length=10)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_non_satisfaites', to='inscriptions.inscriptioneleve')),
            ],
            options={
                'verbose_name': 'Demande non satisfaite',
                'verbose_name_plural': 'Demandes non satisfaites',
                'ordering': ['-date_demande'],
            },
        ),
    ]
