# Generated by Django 6.0.2 on 2026-08-22

from django.db import migrations

# Les 5 étapes RÉELLES du parcours public qui n'avaient encore aucune ligne
# EtapeInscription (seule identite/programme existaient depuis 0002_seed_
# wizard_config) — correction 8 (2026-08-22), "navigation dynamique".
# `ordre` cohérent avec identite=1/programme=2 déjà en base (jamais touchées
# ici, get_or_create non destructif) — categorie_age AVANT (0), le reste
# APRÈS (3-6), dans l'ordre réel actuel du parcours.
ETAPES_MANQUANTES = [
    ('categorie_age', 'اختيار الفئة العمرية', 0),
    ('groupe', 'اختيار المجموعة', 3),
    ('abonnement', 'اختيار الاشتراك', 4),
    ('paiement', 'الدفع', 5),
    ('confirmation', 'التأكيد', 6),
]


def creer_etapes_manquantes(apps, schema_editor):
    """Sans ceci, /dashboard/admin/etapes-inscription/ ne listait que 2
    étapes sur 7 réelles (bug signalé le 2026-08-22) — get_or_create : ne
    touche jamais identite/programme déjà en base, jamais une 2e ligne créée
    si une migration future retombe dessus par erreur."""
    EtapeInscription = apps.get_model('registration', 'EtapeInscription')
    for code, titre, ordre in ETAPES_MANQUANTES:
        EtapeInscription.objects.get_or_create(code=code, defaults={'titre': titre, 'ordre': ordre, 'est_actif': True})


def ne_rien_faire_au_retour_arriere(apps, schema_editor):
    """Reverse volontairement no-op — même principe que 0002_seed_wizard_
    config (voir sa docstring) : un مدير a pu depuis attacher des ChampInscription/
    ConfigurationChampStructurel à l'une de ces étapes (PROTECT), les
    supprimer romprait ces relations sans raison de le faire lors d'un
    retour en arrière de migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_message_aucun_groupe_exact_plus_concret'),
    ]

    operations = [
        migrations.RunPython(creer_etapes_manquantes, ne_rien_faire_au_retour_arriere),
    ]
