# Generated by Django 6.0.2 on 2026-08-23 15:36
#
# Retrait de RegleCondition (chantier du 2026-08-23) — vérifié avant
# suppression : 0 ligne créée depuis la mise en place du modèle (aucune
# migration de seed ne le peuple, base réelle vide au moment de ce
# commit), et le seul cas d'usage qui aurait pu la justifier (masquer
# l'étape "اختيار المجموعة" quand l'élève choisit فردي) est en réalité
# géré par une condition Python fixe dans registration.views.wizard_groupe,
# jamais par une RegleCondition. Suppression définitive, aucune donnée
# réelle perdue — voir registration.models.__doc__ pour le détail complet
# de la décision.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_seed_etapes_manquantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegleCondition',
        ),
    ]
