# Generated by Django 6.0.2 on 2026-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_supprimer_reglecondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='champinscription',
            name='valeur_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='champinscription',
            name='valeur_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
