# Generated by Django 6.0.2 on 2026-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_champ_inscription_bornes_numeriques'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandenonsatisfaite',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='demandenonsatisfaite',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demandenonsatisfaite',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
