# Generated by Django 6.0.2 on 2026-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_backfill_titre_intro_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationinscription',
            name='texte_attente_groupe',
            field=models.TextField(blank=True),
        ),
    ]
