# Generated by Django 6.0.2 on 2026-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_backfill_message_bienvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationinscription',
            name='afficher_disponibilites_si_attente',
            field=models.BooleanField(default=True),
        ),
    ]
