# Generated by Django 6.0.2 on 2026-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_presentationinscription_afficher_disponibilites_si_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationinscription',
            name='bouton_texte_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='bouton_texte_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='intro_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='intro_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='message_aucun_groupe_exact_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='message_aucun_groupe_exact_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='message_bienvenue_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='message_bienvenue_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='texte_attente_groupe_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='texte_attente_groupe_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='titre_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='presentationinscription',
            name='titre_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
