# Generated by Django 6.0.2 on 2026-08-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_presentationinscription_bouton_texte_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champinscription',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='champinscription',
            name='label_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='label_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='message_erreur_regex_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='message_erreur_regex_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='placeholder_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='placeholder_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='texte_aide_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='configurationchampstructurel',
            name='texte_aide_fr',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='critere',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='critere',
            name='label_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='critereoption',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='critereoption',
            name='label_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etapeinscription',
            name='titre_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etapeinscription',
            name='titre_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
