# Generated by Django 6.0.2 on 2026-03-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe_cible', models.CharField(choices=[('homme', 'ذكر'), ('femme', 'أنثى'), ('mixte', 'مختلط')], default='mixte', max_length=10)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('jour_1', models.CharField(choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=5)),
                ('heure_debut_1', models.TimeField()),
                ('heure_fin_1', models.TimeField()),
                ('jour_2', models.CharField(choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=5)),
                ('heure_debut_2', models.TimeField()),
                ('heure_fin_2', models.TimeField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('individuel', 'Individuel'), ('collectif', 'Collectif')], max_length=20)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('capacite_max', models.IntegerField(default=10)),
                ('jour_1', models.CharField(choices=[('lun', 'Lundi'), ('mar', 'Mardi'), ('mer', 'Mercredi'), ('jeu', 'Jeudi'), ('ven', 'Vendredi'), ('sam', 'Samedi'), ('dim', 'Dimanche')], max_length=10)),
                ('heure_1', models.CharField(choices=[('07h', '07:00'), ('09h', '09:00'), ('11h', '11:00'), ('13h', '13:00'), ('15h', '15:00'), ('17h', '17:00'), ('19h', '19:00'), ('21h', '21:00')], max_length=5)),
                ('jour_2', models.CharField(choices=[('lun', 'Lundi'), ('mar', 'Mardi'), ('mer', 'Mercredi'), ('jeu', 'Jeudi'), ('ven', 'Vendredi'), ('sam', 'Samedi'), ('dim', 'Dimanche')], max_length=10)),
                ('heure_2', models.CharField(choices=[('07h', '07:00'), ('09h', '09:00'), ('11h', '11:00'), ('13h', '13:00'), ('15h', '15:00'), ('17h', '17:00'), ('19h', '19:00'), ('21h', '21:00')], max_length=5)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('eleves', models.ManyToManyField(blank=True, related_name='groupes', to='accounts.eleve')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='accounts.prof')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('rattrapage', 'Rattrapage'), ('revision', 'Révision')], max_length=20)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='courses.groupe')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.superviseur')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lun', 'Lundi'), ('mar', 'Mardi'), ('mer', 'Mercredi'), ('jeu', 'Jeudi'), ('ven', 'Vendredi'), ('sam', 'Samedi'), ('dim', 'Dimanche')], max_length=10)),
                ('heure', models.CharField(choices=[('07h', '07:00'), ('09h', '09:00'), ('11h', '11:00'), ('13h', '13:00'), ('15h', '15:00'), ('17h', '17:00'), ('19h', '19:00'), ('21h', '21:00')], max_length=5)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='accounts.prof')),
            ],
            options={
                'unique_together': {('prof', 'jour', 'heure')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'حاضر'), ('absent_excuse', 'غائب بعذر'), ('absent', 'غائب بدون عذر')], default='present', max_length=20)),
                ('quantite_memorisee', models.CharField(blank=True, max_length=200)),
                ('quantite_revisee', models.CharField(blank=True, max_length=200)),
                ('note_memorisation', models.CharField(blank=True, choices=[('mumtaz', 'ممتاز'), ('hasan', 'حسن'), ('mutawassit', 'متوسط'), ('yuid', 'يعيد')], max_length=20)),
                ('note_revision', models.CharField(blank=True, choices=[('mumtaz', 'ممتاز'), ('hasan', 'حسن'), ('mutawassit', 'متوسط'), ('yuid', 'يعيد')], max_length=20)),
                ('remarque', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='accounts.eleve')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='courses.seance')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('seance', 'eleve')},
            },
        ),
    ]
