# Generated by Django 6.0.2 on 2026-03-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='heure_1',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='heure_2',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='jour_1',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='jour_2',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='type',
        ),
        migrations.AddField(
            model_name='groupe',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='courses.creneau'),
        ),
    ]
