# Generated by Django 6.0.2 on 2026-03-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_remove_groupe_heure_1_remove_groupe_heure_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='niveau',
        ),
        migrations.AddField(
            model_name='groupe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='accounts.prof'),
        ),
    ]
