# Generated by Django 6.0.2 on 2026-07-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_groupe_niveau_groupe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='remarque',
            field=models.TextField(blank=True, help_text="Raison d'une exception: annulation ou déplacement (prof malade, vacances...)."),
        ),
    ]
