# Generated by Django 6.0.2 on 2026-07-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_seance_remarque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='quantite_memorisee',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='quantite_revisee',
        ),
        migrations.AddField(
            model_name='presence',
            name='ayah_debut_memorisation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='ayah_debut_revision',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='ayah_fin_memorisation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='ayah_fin_revision',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='sourate_memorisee',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='sourate_revisee',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
