# Generated by Django 6.0.2 on 2026-07-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assigner_profs_aux_superviseurs_existants'),
        ('courses', '0005_remove_presence_quantite_memorisee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModificationDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_matrice', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_disponibilite', to='accounts.prof')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='accounts.prof')),
            ],
            options={
                'verbose_name': 'Disponibilité du professeur',
                'verbose_name_plural': 'Disponibilités des professeurs',
                'unique_together': {('prof', 'jour_semaine', 'heure_debut')},
            },
        ),
        migrations.DeleteModel(
            name='Disponibilite',
        ),
    ]
