# Generated by Django 6.0.2 on 2026-07-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assigner_profs_aux_superviseurs_existants'),
        ('courses', '0006_demandemodificationdisponibilite_disponibiliteprof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='accounts.eleve')),
            ],
            options={
                'verbose_name': "Disponibilité de l'élève",
                'verbose_name_plural': 'Disponibilités des élèves',
                'unique_together': {('eleve', 'jour_semaine', 'heure_debut')},
            },
        ),
    ]
