# Generated by Django 6.0.2 on 2026-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_disponibiliteeleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='type_seance',
            field=models.CharField(choices=[('hifz', 'الحفظ والمراجعة وتعلم أحكام التجويد'), ('tathbit', 'التثبيت وتعلم أحكام التجويد')], default='hifz', max_length=20),
        ),
    ]
