# Generated by Django 6.0.2 on 2026-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_creneau_type_seance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='note_memorisation',
            field=models.CharField(blank=True, choices=[('mumtaz', 'ممتاز'), ('hasan_jiddan', 'حسن جدا'), ('hasan', 'حسن'), ('mustahsan', 'مستحسن'), ('mutawassit', 'متوسط'), ('doun_mutawassit', 'دون متوسط')], max_length=20),
        ),
        migrations.AlterField(
            model_name='presence',
            name='note_revision',
            field=models.CharField(blank=True, choices=[('mumtaz', 'ممتاز'), ('hasan_jiddan', 'حسن جدا'), ('hasan', 'حسن'), ('mustahsan', 'مستحسن'), ('mutawassit', 'متوسط'), ('doun_mutawassit', 'دون متوسط')], max_length=20),
        ),
    ]
