# Generated by Django 6.0.2 on 2026-07-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_migrer_notes_yuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='remarque_generale',
            field=models.TextField(blank=True, help_text='Remarque du prof sur la séance dans son ensemble (distincte des remarques par élève).'),
        ),
    ]
