# Generated by Django 6.0.2 on 2026-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_seance_remarque_generale'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='riwaya',
            field=models.CharField(choices=[('warsh', 'ورش'), ('hafs', 'حفص')], default='hafs', max_length=10),
        ),
        migrations.AddField(
            model_name='groupe',
            name='type_capacite',
            field=models.CharField(choices=[('groupe', 'جماعي'), ('individuel', 'فردي')], default='groupe', max_length=10),
        ),
    ]
