# Generated by Django 6.0.2 on 2026-07-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_creneau_riwaya_groupe_type_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='lien_reunion',
            field=models.URLField(blank=True),
        ),
    ]
