# Generated by Django 6.0.2 on 2026-07-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_groupe_lien_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='consigne_prochaine_seance',
            field=models.TextField(blank=True),
        ),
    ]
