# Generated by Django 6.0.2 on 2026-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_presence_consigne_prochaine_seance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifRemuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_capacite', models.CharField(choices=[('groupe', 'جماعي'), ('individuel', 'فردي')], max_length=10)),
                ('tranche_age', models.CharField(choices=[('enfant', 'طفل'), ('adulte', 'بالغ')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tarif de rémunération',
                'verbose_name_plural': 'Tarifs de rémunération',
                'unique_together': {('type_capacite', 'tranche_age')},
            },
        ),
    ]
