# Generated by Django 6.0.2 on 2026-07-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_migrer_charte_vers_champs_structures'),
        ('courses', '0016_seed_tarifs_remuneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_reference', models.DateField()),
                ('memorisation', models.TextField(blank=True)),
                ('revision', models.TextField(blank=True)),
                ('remarques_discipline', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_mensuels', to='accounts.eleve')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_mensuels', to='accounts.prof')),
            ],
            options={
                'verbose_name': 'Bilan mensuel',
                'verbose_name_plural': 'Bilans mensuels',
                'ordering': ['-mois_reference'],
                'unique_together': {('eleve', 'prof', 'mois_reference')},
            },
        ),
    ]
