# Generated by Django 6.0.2 on 2026-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_bilanmensuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemodificationdisponibilite',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('approuvee', 'موافَق عليها'), ('rejetee', 'مرفوضة')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='statut',
            field=models.CharField(choices=[('actif', 'نشط'), ('archive', 'مؤرشف')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'مخططة'), ('terminee', 'منتهية'), ('annulee', 'ملغاة')], default='planifiee', max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='type',
            field=models.CharField(choices=[('normal', 'عادية'), ('rattrapage', 'حصة تعويضية'), ('revision', 'مراجعة')], max_length=20),
        ),
    ]
