# Generated by Django 6.0.2 on 2026-07-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_programme_general_deux_versions'),
        ('courses', '0019_evaluation_numerique_et_consignes_separees'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueGroupeEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_groupes', to='accounts.eleve')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_eleves', to='courses.groupe')),
            ],
            options={
                'verbose_name': "Historique d'appartenance à un groupe",
                'verbose_name_plural': "Historiques d'appartenance aux groupes",
                'ordering': ['-date_debut'],
            },
        ),
    ]
