# Generated by Django 6.0.2 on 2026-08-04 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_historiquegroupeeleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ar', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Critère d'évaluation élève",
                'verbose_name_plural': "Critères d'évaluation élève",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='NotePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.critereeleve')),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_criteres', to='courses.presence')),
            ],
            options={
                'verbose_name': 'Note par critère (élève)',
                'verbose_name_plural': 'Notes par critère (élève)',
                'unique_together': {('presence', 'critere')},
            },
        ),
    ]
