# Generated by Django 6.0.2 on 2026-08-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_seed_criteres_eleves_et_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglageLienSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marge_avant_minutes', models.PositiveIntegerField(default=10)),
                ('marge_apres_minutes', models.PositiveIntegerField(default=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_modification_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réglage du lien de séance',
                'verbose_name_plural': 'Réglage du lien de séance',
            },
        ),
    ]
