# Generated by Django 6.0.2 on 2026-08-08 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_reglagelienseance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('groupe', 'مجموعة'), ('creneau', 'حلقة')], max_length=20)),
                ('nom_objet', models.CharField(max_length=200)),
                ('id_objet', models.IntegerField()),
                ('resume_donnees_perdues', models.TextField()),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حذف',
                'verbose_name_plural': 'سجل الحذف',
                'ordering': ['-date_suppression'],
            },
        ),
    ]
