# Generated by Django 6.0.2 on 2026-08-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_journalsuppression'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalSuppression',
        ),
    ]
