# Generated by Django 6.0.2 on 2026-08-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_element_hakiba_refonte'),
        ('courses', '0025_delete_journalsuppression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanmensuel',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_mensuels', to='accounts.prof'),
        ),
    ]
