# Generated by Django 6.0.2 on 2026-08-13 23:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_options_prof_accounts_prof_ville_trgm_and_more'),
        ('courses', '0026_alter_bilanmensuel_prof'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='courses_groupe_nom_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
