# Generated by Django 6.0.2 on 2026-08-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_groupe_courses_groupe_nom_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lien Google Meet',
                'verbose_name_plural': 'Liens Google Meet',
                'ordering': ['libelle', 'id'],
            },
        ),
        migrations.AddField(
            model_name='groupe',
            name='lien_meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='courses.lienmeet'),
        ),
    ]
