# Generated by Django 6.0.2 on 2026-08-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_lienmeet_groupe_lien_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='lien_meet_exceptionnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_exceptionnelles', to='courses.lienmeet'),
        ),
    ]
