# Generated by Django 6.0.2 on 2026-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_seance_lien_meet_exceptionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='categorie',
            field=models.CharField(blank=True, choices=[('femmes_adultes', 'الطالبات البالغات'), ('hommes_adultes', 'الطلاب البالغون'), ('mineurs', 'الطلاب القاصرون')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='groupe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='groupes_photos/'),
        ),
    ]
