# Generated by Django 6.0.2 on 2026-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_groupe_categorie_groupe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='categorie',
            field=models.CharField(blank=True, choices=[('femmes_adultes', 'الطالبات البالغات'), ('hommes_adultes', 'الطلاب البالغون'), ('mineurs', 'الأطفال')], default='', max_length=20),
        ),
    ]
