# Generated by Django 6.0.2 on 2026-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_groupe_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
