# Generated by Django 6.0.2 on 2026-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_creneau_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='resultat_memorisation',
            field=models.CharField(blank=True, choices=[('valide', 'ينتقل'), ('a_refaire', 'يعيد')], default='valide', max_length=10),
        ),
        migrations.AddField(
            model_name='presence',
            name='resultat_revision',
            field=models.CharField(blank=True, choices=[('valide', 'ينتقل'), ('a_refaire', 'يعيد')], default='valide', max_length=10),
        ),
    ]
