# Generated by Django 6.0.2 on 2026-08-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_backfill_groupe_categorie_depuis_creneau'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=5)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courses.creneau')),
            ],
            options={
                'verbose_name': 'Créneau hebdomadaire (occurrence)',
                'verbose_name_plural': 'Créneaux hebdomadaires (occurrences)',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
