# Generated by Django 6.0.2 on 2026-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_backfill_creneauslot_depuis_jour_1_jour_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='heure_debut_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='heure_debut_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='heure_fin_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='heure_fin_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='jour_1',
            field=models.CharField(blank=True, choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='jour_2',
            field=models.CharField(blank=True, choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=5, null=True),
        ),
    ]
