# Generated by Django 6.0.2 on 2026-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_creneau_heure_debut_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='cache_du_wizard_public',
            field=models.BooleanField(default=False),
        ),
    ]
