# Generated by Django 6.0.2 on 2026-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_groupe_cache_du_wizard_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionNbSeances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveSmallIntegerField(unique=True)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Option de nombre de séances/semaine',
                'verbose_name_plural': 'Options de nombre de séances/semaine',
                'ordering': ['valeur'],
            },
        ),
        migrations.CreateModel(
            name='TarifRemunerationIndividuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('enfant', 'طفل'), ('adulte', 'بالغ')], max_length=10, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tarif de rémunération (individuel)',
                'verbose_name_plural': 'Tarifs de rémunération (individuel)',
                'ordering': ['tranche_age'],
            },
        ),
        migrations.AlterModelOptions(
            name='tarifremuneration',
            options={'verbose_name': 'Tarif de rémunération (déprécié)', 'verbose_name_plural': 'Tarifs de rémunération (déprécié)'},
        ),
        migrations.CreateModel(
            name='TarifRemunerationGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('enfant', 'طفل'), ('adulte', 'بالغ')], max_length=10)),
                ('nb_slots', models.PositiveSmallIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif de rémunération (groupe)',
                'verbose_name_plural': 'Tarifs de rémunération (groupe)',
                'ordering': ['tranche_age', 'nb_slots'],
                'unique_together': {('tranche_age', 'nb_slots')},
            },
        ),
    ]
