# Generated by Django 6.0.2 on 2026-08-27 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_prof_presentation_publique_and_more'),
        ('courses', '0040_seed_nb_seances_et_tarifs_remuneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeChangementHalaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('validee', 'مقبولة'), ('refusee', 'مرفوضة')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_changement_halaka', to='accounts.eleve')),
                ('groupe_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.groupe')),
                ('groupe_demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_changement_halaka_visant_ce_groupe', to='courses.groupe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de changement de halaka',
                'verbose_name_plural': 'Demandes de changement de halaka',
                'ordering': ['-date_demande'],
            },
        ),
    ]
