# Generated by Django 6.0.2 on 2026-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_demandechangementhalaka'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupe',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupe',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupe',
            name='nom_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
