# Generated by Django 6.0.2 on 2026-08-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_groupe_description_en_groupe_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critereeleve',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='critereeleve',
            name='nom_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
