# Generated by Django 6.0.2 on 2026-08-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_critereeleve_nom_en_critereeleve_nom_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creneau',
            name='nom_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lienmeet',
            name='libelle_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lienmeet',
            name='libelle_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
