# Generated by Django 6.0.2 on 2026-09-05 08:37

# Audit du 2026-09-05 (chantier « fusion horaire/groupe » du 2026-09-04) :
# l'invariant « un Creneau n'appartient jamais qu'à un seul Groupe » n'était
# jusqu'ici garanti que par le code des vues (groupe_ajouter/groupe_modifier),
# pas par la base — un ForeignKey ordinaire laissait /admin/ (Creneau et
# Groupe enregistrés sans restriction, voir courses/admin.py) réassigner le
# même Creneau à 2 Groupe, ce qui aurait fait supprimer silencieusement le
# Creneau de l'un des deux au prochain groupe_modifier de l'autre (SET_NULL).
# unique=True fait respecter cet invariant par Postgres lui-même — préférée à
# OneToOneField pour ne pas changer l'accesseur inverse `creneau.groupes`
# (encore utilisé tel quel par courses.utils.creneau_peut_etre_supprime).
# Nécessite la migration 0045 (dépliage des créneaux déjà partagés) déjà
# appliquée avant celle-ci, sans quoi la contrainte échouerait à la pose.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_dedupliquer_creneaux_partages_entre_groupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='courses.creneau', unique=True),
        ),
    ]
