# Generated by Django 6.0.2 on 2026-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_backfill_type_lie_criteres_eleves'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilCriteresSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(unique=True)),
                ('criteres', models.ManyToManyField(blank=True, related_name='profils_seance', to='courses.critereeleve')),
            ],
            options={
                'verbose_name': 'Profil de critères par position de séance',
                'verbose_name_plural': 'Profils de critères par position de séance',
                'ordering': ['position'],
            },
        ),
    ]
