# Generated by Django 6.0.2 on 2026-09-12 18:27
#
# STRUCTURELLE UNIQUEMENT — aucune conversion de données volontairement.
# Les 2 lignes ProfilCriteresSeance existantes (position=1, position=2,
# seedées par la migration 0051) restent group=None/nb_seances_semaine=None
# après cette migration : elles deviennent des lignes orphelines, jamais lues
# par la nouvelle résolution de Seance.criteres_applicables (qui cherche
# désormais (groupe=None, nb_seances_semaine=<valeur réelle>, position=...)).
# En pratique, dès le premier accès réel à chaque séance, criteres_applicables
# recrée les bons profils Niveau 1 à la volée avec le même contenu par défaut
# (voir Seance._defaut_criteres_pour_nouvelle_position — identique aux
# 2 lignes actuelles, vérifié le 2026-09-12 : aucune personnalisation
# n'a encore été faite par l'admin, le contenu stocké == le contenu recalculé
# depuis CritereEleve.type_lie). Une migration de données séparée (suppression
# des 2 lignes orphelines position=1/2, une fois le mapping
# nb_seances_semaine confirmé avec le client pour les 4 groupes sans créneau
# — voir l'échange du 2026-09-12) sera ajoutée après validation explicite,
# plutôt que de deviner ce mapping ici.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_seed_profils_criteres_seance_1_et_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcriteresseance',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profils_criteres_seance', to='courses.groupe'),
        ),
        migrations.AddField(
            model_name='profilcriteresseance',
            name='nb_seances_semaine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilcriteresseance',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='profilcriteresseance',
            constraint=models.UniqueConstraint(condition=models.Q(('groupe__isnull', True)), fields=('nb_seances_semaine', 'position'), name='uniq_commun_nbseances_position'),
        ),
        migrations.AddConstraint(
            model_name='profilcriteresseance',
            constraint=models.UniqueConstraint(condition=models.Q(('groupe__isnull', False)), fields=('groupe', 'position'), name='uniq_groupe_position'),
        ),
    ]
