# Generated by Django 6.0.2 on 2026-09-13 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_seed_dernieres_visites_notification_paiements_acceptes'),
        ('courses', '0054_seance_date_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='hizb_travaille',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='presence',
            name='thumn_travaille',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.CreateModel(
            name='ProgressionMemorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizb_depart', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('thumn_depart', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('sens', models.CharField(choices=[('tasaudi', 'تصاعدي'), ('tanazuli', 'تنازلي')], max_length=10)),
                ('hizb_actuel', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('thumn_actuel', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('terminee', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression_memorisation', to='accounts.eleve')),
            ],
            options={
                'verbose_name': 'Progression de mémorisation',
                'verbose_name_plural': 'Progressions de mémorisation',
            },
        ),
    ]
