# Generated by Django 6.0.2 on 2026-09-13 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_presence_hizb_travaille_presence_thumn_travaille_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='hizb_travaille',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='thumn_travaille',
        ),
        migrations.AddField(
            model_name='progressionmemorisation',
            name='seance_initiale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.seance'),
        ),
        migrations.CreateModel(
            name='PartieEvaluee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizb', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('thumn', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('resultat', models.CharField(choices=[('valide', 'ينتقل'), ('a_refaire', 'يعيد')], default='valide', max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_evaluees', to='courses.presence')),
            ],
            options={
                'verbose_name': 'Partie évaluée',
                'verbose_name_plural': 'Parties évaluées',
                'ordering': ['ordre'],
            },
        ),
    ]
