# Generated by Django 6.0.2 on 2026-09-14 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_remove_presence_hizb_travaille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionmemorisation',
            name='derniere_seance_travaillee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.seance'),
        ),
        migrations.AddField(
            model_name='progressionmemorisation',
            name='hizb_avant_derniere_seance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressionmemorisation',
            name='thumn_avant_derniere_seance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TravailSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizb_debut', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('thumn_debut', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('hizb_fin', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('thumn_fin', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travail_seances', to='courses.presence')),
            ],
            options={
                'verbose_name': 'Travail de séance (حفظ)',
                'verbose_name_plural': 'Travaux de séance (حفظ)',
                'ordering': ['ordre'],
            },
        ),
    ]
