# Generated by Django 6.0.2 on 2026-08-15 23:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_alter_user_options_prof_accounts_prof_ville_trgm_and_more'),
        ('courses', '0027_groupe_courses_groupe_nom_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'مسودة'), ('publie', 'منشور'), ('ferme', 'مغلق')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(help_text='Disponible à partir de.')),
                ('date_limite', models.DateTimeField(help_text="Disponible jusqu'à.")),
                ('duree_minutes', models.PositiveIntegerField(help_text="Durée maximale de passage, en minutes, une fois l'examen commencé par un élève.", validators=[django.core.validators.MinValueValidator(1)])),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='courses.groupe')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='accounts.prof')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'قيد الإنجاز'), ('soumise', 'مُقدَّمة')], default='en_cours', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('soumission_automatique', models.BooleanField(default=False)),
                ('note_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies_examens', to='accounts.eleve')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='examens.examen')),
            ],
            options={
                'verbose_name': 'Copie',
                'verbose_name_plural': 'Copies',
                'unique_together': {('examen', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('choix', 'اختيار من متعدد'), ('vrai_faux', 'صح / خطأ'), ('texte', 'إجابة نصية'), ('audio', 'إجابة صوتية')], max_length=10)),
                ('enonce', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reponse_correcte_bool', models.BooleanField(blank=True, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examens.examen')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChoixQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='examens.question')),
            ],
            options={
                'verbose_name': 'Choix de question',
                'verbose_name_plural': 'Choix de questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_bool', models.BooleanField(blank=True, null=True)),
                ('reponse_texte', models.TextField(blank=True)),
                ('reponse_audio', models.FileField(blank=True, null=True, upload_to='examens_audio/%Y/%m/')),
                ('nom_fichier_audio_original', models.CharField(blank=True, default='', max_length=255)),
                ('statut_correction', models.CharField(choices=[('auto', 'مصححة تلقائياً'), ('a_corriger', 'بانتظار التصحيح'), ('corrigee', 'مصححة')], default='a_corriger', max_length=20)),
                ('points_obtenus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaire_prof', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(auto_now=True)),
                ('copie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='examens.copie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='examens.question')),
                ('reponse_choix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='examens.choixquestion')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'unique_together': {('copie', 'question')},
            },
        ),
    ]
