# Generated by Django 6.0.2 on 2026-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='nom_fichier_video_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reponse',
            name='reponse_video',
            field=models.FileField(blank=True, null=True, upload_to='examens_video/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('choix', 'اختيار من متعدد'), ('vrai_faux', 'صح / خطأ'), ('texte', 'إجابة نصية'), ('audio', 'إجابة صوتية'), ('video', 'إجابة فيديو')], max_length=10),
        ),
    ]
